import { test, type Page, type TestInfo } from '@playwright/test';
import { expect, assertionsPerformed } from './assertions';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

type Check = { description: string; assert: () => Promise<unknown> };
type CompletedStep = { id: string; title: string; checks: string[] };
const scenarios = new WeakMap<TestInfo, TestSteps>();

export function assertStepsFinished(info: TestInfo) {
  const steps = scenarios.get(info);
  if (!steps || !steps.finished) throw new Error('Every scenario must construct TestSteps, run semantic steps, and call finish().');
}

export class TestSteps {
  private completed: CompletedStep[] = [];
  finished = false;

  constructor(
    private page: Page,
    private info: TestInfo,
    private title: string,
    private description: string
  ) {
    if (scenarios.has(info)) throw new Error('Use one TestSteps walkthrough per scenario.');
    scenarios.set(info, this);
  }

  async step(id: string, title: string, checks: Check[]) {
    if (this.finished || !title.trim() || !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(id) || !checks.length) {
      throw new Error('Each step needs a stable kebab-case ID and semantic checks.');
    }
    if (this.completed.some((step) => step.id.endsWith(`-${id}`))) throw new Error('Duplicate step ID');
    const numberedId = `${String(this.completed.length).padStart(3, '0')}-${id}`;
    await test.step(title, async () => {
      for (const check of checks) await test.step(check.description, async () => {
        if (!check.description.trim()) throw new Error('Semantic checks require a description.');
        const before = assertionsPerformed();
        await check.assert();
        if (assertionsPerformed() === before) throw new Error('Each semantic check must execute an expect matcher.');
      });
      await expect(this.page.locator('body')).toBeVisible();
      // Readiness is a condition on local fonts, not a delay or screenshot-only style change.
      await expect(this.page.locator('html')).toHaveJSProperty('lang', 'en');
      expect(await this.page.evaluate(() => document.fonts.status)).toBe('loaded');
      const layoutProblems = await this.page.evaluate(() => {
        const errors: string[] = [];
        const root = document.documentElement;
        if (root.scrollWidth > innerWidth || root.scrollHeight > innerHeight) errors.push('Splash overflows viewport');
        const modal = document.querySelector('dialog[open]');
        const scope = modal ?? document.querySelector('main')!;
        for (const element of scope.querySelectorAll<HTMLElement>('h1, h2, p, li, button, footer')) {
          if (!element.checkVisibility()) continue;
          const rect = element.getBoundingClientRect();
          if (rect.left < 0 || rect.top < 0 || rect.right > innerWidth || rect.bottom > innerHeight) {
            errors.push(`Clipped ${element.tagName}: ${element.textContent?.trim()}`);
          }
          if (element.tagName === 'BUTTON' && (rect.width < 44 || rect.height < 44)) errors.push('Touch target smaller than 44px');
        }
        const controls = Array.from(scope.querySelectorAll<HTMLElement>('button, a, input, select')).filter((element) => element.checkVisibility());
        for (let left = 0; left < controls.length; left++) {
          for (let right = left + 1; right < controls.length; right++) {
            const a = controls[left].getBoundingClientRect();
            const b = controls[right].getBoundingClientRect();
            if (Math.min(a.right, b.right) > Math.max(a.left, b.left) && Math.min(a.bottom, b.bottom) > Math.max(a.top, b.top)) errors.push('Interactive controls overlap');
          }
        }
        return errors;
      });
      expect(layoutProblems, 'Splash content fits and controls remain reachable').toEqual([]);
      await expect(this.page).toHaveScreenshot(`${numberedId}.png`);
    });
    this.completed.push({ id: numberedId, title, checks: checks.map((check) => check.description) });
  }

  finish() {
    if (this.finished || !this.completed.length) throw new Error('Finish exactly once, after at least one completed step.');
    this.finished = true;
    if (this.info.project.name !== 'desktop') return;
    const content = [
      `# ${this.title}`,
      '',
      '> Generated by TestSteps from the passing browser scenario. Do not edit manually.',
      '',
      this.description,
      ...this.completed.flatMap((step) => [
        '', `## ${step.title}`, '',
        ...step.checks.map((check) => `- ${check}`),
        '', `![Desktop: ${step.title}](screenshots/${step.id}-desktop.png)`,
        '', `![Phone: ${step.title}](screenshots/${step.id}-phone.png)`
      ]),
      ''
    ].join('\n');
    const path = join(dirname(this.info.file), 'README.md');
    if (process.env.UPDATE_E2E_DOCS === '1') writeFileSync(path, content);
    else expect(readFileSync(path, 'utf8'), 'Walkthrough matches the tested steps').toBe(content);
  }
}
